config/routes.rb
Crowdhoster::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  # PAGES
  root                                         to: 'pages#index'

  # USERS
  devise_for :users, { path: 'account', controllers: { registrations: :registrations } }  do
    match '/user/settings',                    to: 'devise/registrations#edit',             as: :user_settings
  end

  # ADMIN
  match '/admin',                      to: 'admin#admin_website',                   as: :admin_website
  namespace :admin do
    resources :campaigns
    post '/payments/:id/refund',                to: 'payments#refund_payment',               as: :admin_payment_refund
  end

  match '/admin/campaigns/:id/copy',           to: 'admin/campaigns#copy',                  as: :admin_campaigns_copy
  match '/admin/campaigns/:id/payments',       to: 'admin/campaigns#payments',              as: :admin_campaigns_payments
  match '/admin/processor-setup',              to: 'admin#admin_processor_setup',           as: :admin_processor_setup
  post '/admin/bank-setup',                    to: 'admin#create_admin_bank_account',       as: :create_admin_bank_account
  get '/admin/bank-setup',                     to: 'admin#admin_bank_account',              as: :admin_bank_account
  delete '/admin/bank-setup',                  to: 'admin#delete_admin_bank_account',       as: :delete_admin_bank_account
  match '/admin/notification-setup',           to: 'admin#admin_notification_setup',        as: :admin_notification_setup
  match '/ajax/verify',                        to: 'admin#ajax_verify',                     as: :ajax_verify

  # CAMPAIGNS
  match '/:id/checkout/amount',                to: 'campaigns#checkout_amount',             as: :checkout_amount
  match '/:id/checkout/payment',               to: 'campaigns#checkout_payment',            as: :checkout_payment
  match '/:id/checkout/process',               to: 'campaigns#checkout_process',            as: :checkout_process
  match '/:id/checkout/confirmation',          to: 'campaigns#checkout_confirmation',       as: :checkout_confirmation
  match '/:id',                                to: 'campaigns#home',                        as: :campaign_home


  namespace :api, defaults: {format: 'json'} do
    scope module: :v0  do
      resources :campaigns, only: :show do
        resources :payments, only: :index
      end
    end
  end
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  has_many :faqs, dependent: :destroy, :order => 'sort_order'
  has_many :payments
  has_many :rewards

  attr_accessible :name, :goal_type, :goal_dollars, :goal_orders,  :expiration_date, :ct_campaign_id, :media_type,
                  :main_image, :main_image_delete, :video_embed_id, :video_placeholder, :video_placeholder_delete,
                  :contributor_reference, :progress_text, :primary_call_to_action_button, :primary_call_to_action_description,
                  :secondary_call_to_action_button, :secondary_call_to_action_description, :main_content,
                  :checkout_sidebar_content, :confirmation_page_content, :confirmation_email_content,
                  :tweet_text, :facebook_title, :facebook_description,  :facebook_image, :facebook_image_delete,
                  :payment_type, :fixed_payment_amount, :min_payment_amount, :apply_processing_fee,
                  :stats_number_of_contributions, :stats_raised_amount, :stats_tilt_percent,
                  :stats_unique_contributors, :published_flag, :collect_shipping, :production_flag,
                  :include_rewards, :reward_reference, :collect_additional_info, :additional_info_label,
                  :include_comments, :comments_shortname

  attr_accessor :main_image_delete, :video_placeholder_delete, :facebook_image_delete

  validates :name, :expiration_date, presence: true
  validates :min_payment_amount, numericality: { greater_than_or_equal_to: 1.0 }
  validates :fixed_payment_amount, numericality: { greater_than_or_equal_to: 1.0 }
  validate :expiration_date_cannot_be_in_the_past, :payments_can_be_activated

  before_validation { main_image.clear if main_image_delete == '1' }
  before_validation { video_placeholder.clear if video_placeholder_delete == '1' }
  before_validation { facebook_image.clear if facebook_image_delete == '1' }

  has_attached_file :main_image,
                    styles: { main: "512x385!", medium: "640x360!", small: "190x143!", thumb: "100x100#" }

  has_attached_file :video_placeholder,
                    styles: { main: "512x385!", medium: "640x360!", thumb: "100x100#" }  #The hash indicates cropping, use ! for forced scaling

  has_attached_file :facebook_image,
                    styles: { thumb: "100x100#" }

  before_save :set_min_amount

  def update_api_data(campaign)
    self.ct_campaign_id = campaign['id']
    self.stats_number_of_contributions = campaign['stats']['number_of_contributions']
    self.stats_raised_amount = campaign['stats']['raised_amount']/100.0
    self.stats_tilt_percent = campaign['stats']['tilt_percent']
    self.stats_unique_contributors = campaign['stats']['unique_contributors']
    self.is_tilted = campaign['is_tilted'].to_i == 0 ? false : true
    self.is_expired = campaign['is_expired'].to_i == 0 ? false : true
    self.is_paid = campaign['is_paid'].to_i == 0 ? false : true
  end

  def set_goal
    if self.goal_type == 'orders'
      self.goal_dollars = ((self.fixed_payment_amount * self.goal_orders)*100).round/100.0
    end
  end

  def expired?
    self.expiration_date < Time.current
  end

  def orders
    (self.stats_raised_amount / self.fixed_payment_amount).to_i
  end

  def rewards?
    (self.payment_type != 'fixed' && self.rewards.length > 0)
  end

  def payments_completed
    self.payments.where(:status => %w(authorized charged released rejected refunded offline))
  end

  def payments_successful
    # 'rejected' is a post-tilt state, so they are included in successful payments.
    self.payments.where(:status => %w(authorized charged released rejected offline))
  end

  def raised_amount
    self.payments_successful.sum(:amount)/100.0
  end

  def number_of_contributions
    self.payments_successful.count
  end

  def tilt_percent
    (raised_amount / goal_dollars) * 100.0
  end

  private

  def set_min_amount
    if self.payment_type == "any"
      self.min_payment_amount = 1.0
    end
  end

  def expiration_date_cannot_be_in_the_past
    if self.expiration_date_changed? && !self.expiration_date.blank? && self.expiration_date < Time.current
      errors.add(:expiration_date, "can't be in the past")
    end
  end

  def payments_can_be_activated
      if self.production_flag && !Settings.find_by_id(1).payments_activated?
        errors.add(:base, "cannot activate payments")
      end
  end

end

app/controllers/admin/campaigns_controller.rb
class Admin::CampaignsController < ApplicationController
  layout "admin"
  before_filter :authenticate_user!
  before_filter :verify_admin

  def index
    @campaigns = Campaign.order("created_at ASC")
  end

  def new
    @campaign = Campaign.new
  end

  def copy
    old_campaign = Campaign.find(params[:id])
    @campaign = old_campaign.dup
    @campaign.published_flag = false
    @campaign.production_flag = false

    begin
      campaign = {
        title: @campaign.name,
        tilt_amount: @campaign.goal_dollars*100,
        expiration_date: @campaign.expiration_date,
        user_id: @settings.ct_sandbox_admin_id,
        billing_statement_text: @settings.billing_statement_text
      }
      Crowdtilt.sandbox
      response = Crowdtilt.post('/campaigns', {campaign: campaign})
    rescue => exception
      redirect_to admin_campaigns, :flash => { :error => "An error occurred" }
    else
      @campaign.update_api_data(response['campaign'])
      @campaign.save
    end

    # Completely refresh the FAQs
    old_campaign.faqs.each do |faq|
      @campaign.faqs.create question: faq.question, answer: faq.answer
    end

    # Completely refresh the rewards
    old_campaign.rewards.each do |reward|
      @campaign.rewards.create title: reward.title,
                               description: reward.description,
                               delivery_date: reward.delivery_date,
                               number: reward.number,
                               price: reward.price
    end

    render action: "edit"
  end

  def create
    is_default = params[:campaign].delete :is_default
    @campaign = Campaign.new(params[:campaign])

    # Check if the new settings pass validations...if not, re-render form and display errors in flash msg
    if !@campaign.valid?
      message = ''
      @campaign.errors.each do |key, error|
        message = message + key.to_s.humanize + ' ' + error.to_s + ', '
      end
      flash.now[:error] = message[0...-2]
      render action: "new"
      return
    end

     # Set the campaign user id
     ct_user_id = @campaign.production_flag ? @settings.ct_production_admin_id : @settings.ct_sandbox_admin_id

    # calculate the goal amount (in case of a tilt by orders campaign)
    @campaign.set_goal

    # Create a corresponding campaign on the Crowdtilt API
    # If it fails, echo the error message sent by the API back to the user
    # If successful, save the campaign
    begin
      campaign = {
        title: @campaign.name,
        tilt_amount: (@campaign.goal_dollars*100).to_i,
        expiration_date: @campaign.expiration_date,
        user_id: ct_user_id,
        billing_statement_text: @settings.billing_statement_text
      }
      @campaign.production_flag ? Crowdtilt.production(@settings) : Crowdtilt.sandbox
      response = Crowdtilt.post('/campaigns', {campaign: campaign})
    rescue => exception
      flash.now[:error] = exception.to_s
      render action: "new"
      return
    else
      @campaign.update_api_data(response['campaign'])
      @campaign.save

      # Now that we've created the campaign, create new FAQs if any were provided
      if params.has_key?(:faq)
        params[:faq].each do |faq|
          if !faq['question'].empty?
            @campaign.faqs.create question: faq['question'], answer: faq['answer']
          end
        end
      end

      # Now that we've created the campaign, create new Reward Levels if any were provided
      if params.has_key?(:reward)
        params[:reward].each do |reward|
          unless reward['delete'] && reward['delete'] == 'delete'
              @campaign.rewards.create title: reward['title'],
                                       description: reward['description'],
                                       delivery_date: reward['delivery_date'],
                                       number: reward['number'].to_i,
                                       price: reward['price'].to_f
          end
        end
      end

      # Check again for campaign validity now that we've added faqs and rewards
      if !@campaign.valid?
        message = ''
        @campaign.errors.each do |key, error|
          message = message + key.to_s.humanize + ' ' + error.to_s + ', '
        end
        flash.now[:error] = message[0...-2]
        render action: "new"
        return
      end

      # Set default campaign
      if(is_default == "1")
        @settings.default_campaign_id = @campaign.id
      elsif (@settings.default_campaign_id == @campaign.id)
        @settings.default_campaign_id = nil
      end
      @settings.save

      redirect_to campaign_home_url(@campaign), :flash => { :notice => "Campaign updated!" }
      return
    end
  end

  def edit
    @campaign = Campaign.find(params[:id])
  end

  def update
    @campaign = Campaign.find(params[:id])

    is_default = params[:campaign].delete :is_default

    if(is_default =="1")
      @settings.default_campaign_id = @campaign.id
    elsif (@settings.default_campaign_id == @campaign.id)
      @settings.default_campaign_id = nil
    end
    @settings.save

    # We don't immediately update the campaign, becuase the Crowdtilt API may still fail a validation
    @campaign.assign_attributes(params[:campaign])

    # Completely refresh the FAQ data
    @campaign.faqs.destroy_all
    if params.has_key?(:faq)
      params[:faq].each do |faq|
        if !faq['question'].empty?
          @campaign.faqs.create question: faq['question'], answer: faq['answer']
        end
      end
    end

    # Update the Reward Levels
    if params.has_key?(:reward)
      params[:reward].each do |reward|
        if reward['delete'] && reward['delete'] == 'delete'
          if reward['id']
            r = Reward.find(reward['id'])
            r.destroy if(r.payments.length == 0)
          end
        else
          if reward['id']
              r = Reward.find(reward['id'])
              r.title = reward['title']
              r.description = reward['description']
              r.delivery_date = reward['delivery_date']
              r.number = reward['number'].to_i
              r.price = reward['price'].to_f
              unless r.save
                flash.now[:error] = "Invalid rewards"
                render action: "edit"
                return
              end
          else
            @campaign.rewards.create title: reward['title'],
                                     description: reward['description'],
                                     delivery_date: reward['delivery_date'],
                                     number: reward['number'].to_i,
                                     price: reward['price'].to_f
          end
        end
      end
    end

    # Check if the new settings pass validations...if not, re-render form and display errors in flash msg
    if !@campaign.valid?
      message = ''
      @campaign.errors.each do |key, error|
        message = message + key.to_s.humanize + ' ' + error.to_s + ', '
      end
      flash.now[:error] = message[0...-2]
      render action: "edit"
      return
    end

    # Set the campaign user id
     ct_user_id = @campaign.production_flag ? @settings.ct_production_admin_id : @settings.ct_sandbox_admin_id

    #if campaign has been promoted to production, delete all sandbox payments
    if @campaign.production_flag && @campaign.production_flag_changed?
      @campaign.payments.destroy_all
    end

    # calculate the goal amount (in case of a tilt by orders campaign)
    @campaign.set_goal

    # Update the corresponding campaign on the Crowdtilt API
    # If it fails, echo the error message sent by the API back to the user
    # If successful, save the campaign
    begin
      campaign = {
        title: @campaign.name,
        tilt_amount: (@campaign.goal_dollars*100).to_i,
        expiration_date: @campaign.expiration_date,
        billing_statement_text: @settings.billing_statement_text
      }
      # If the campaign has been promoted to production, create a new campaign on the Crowtilt API
      if @campaign.production_flag && @campaign.production_flag_changed?
        campaign[:user_id] = ct_user_id
        Crowdtilt.production(@settings)
        response = Crowdtilt.post('/campaigns', {campaign: campaign})
      else
        @campaign.production_flag ? Crowdtilt.production(@settings) : Crowdtilt.sandbox
        response = Crowdtilt.put('/campaigns/' + @campaign.ct_campaign_id, {campaign: campaign})
      end
    rescue => exception
      flash.now[:error] = exception.to_s
      render action: "edit" and return
    else
      @campaign.update_api_data(response['campaign'])
      @campaign.save
      redirect_to campaign_home_url(@campaign), :flash => { :notice => "Campaign updated!" } and return
    end
  end

  def payments
#     @campaign = Campaign.find(params[:id])
#     page = params[:page] || 1
#
#     #Check if the user is searching for a certain payment_id
#     if params.has_key?(:payment_id) && !params[:payment_id].blank?
#       begin
#         response = Crowdtilt.get('/campaigns/' + @campaign.ct_campaign_id + '/payments/' + params[:payment_id])
#       rescue => exception
#         #This means the payment_id wasn't found, so go ahead and grab all payments
#         response = Crowdtilt.get('/campaigns/' + @campaign.ct_campaign_id + '/payments?page=1&per_page=50')
#         @contributors = response['payments']
#         @page = response['pagination']['page'].to_i
#         @total_pages = response['pagination']['total_pages'].to_i
#         flash.now[:error] = "Contributor not found for " + params[:payment_id]
#       else
#         @contributors = [response['payment']]
#         @page = @total_pages = 1
#       end
#     else
#       response = Crowdtilt.get('/campaigns/' + @campaign.ct_campaign_id + "/payments?page=#{page}&per_page=50")
#       @contributors = @contributors = response['payments']
#       @page = response['pagination']['page'].to_i
#       @total_pages = response['pagination']['total_pages'].to_i

app/controllers/api/v0/campaigns_controller.rb
class Api::V0::CampaignsController < Api::V0::BaseController
  def show
    render json: Campaign.find(params[:id])
  end
end

app/helpers/admin/campaigns_helper.rb
module Admin::CampaignsHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper

  def short_price(price)
    number_with_precision(price, precision: (price*100%100==0.0 ? 0 : 2))
  end
end

app/views/campaigns/checkout_amount.html.erb
<div id="checkout">
  <div class="container content_box clearfix">
    <div class="main_content">
      <h3><a href="<%= campaign_home_path(@campaign) %>"><%= @campaign.name %></a></h3>

      <div class="well checkout_block">
        <form accept-charset="UTF-8" action="<%= checkout_payment_path(@campaign) %>" method="GET" id="amount_form">

          <% if @campaign.payment_type == 'fixed' %>

            <div class="quantity_input">
            <h4 class="amount_header">Please choose a quantity: </h4>
            <br/>

              <span>$<%= number_with_precision(@campaign.fixed_payment_amount, precision: 2) %>&nbsp; x &nbsp;</span>
              <select id="quantity" name="quantity" style="width:65px">
                <option value="01" selected>01</option>
                <option value="02">02</option>
                <option value="03">03</option>
                <option value="04">04</option>
                <option value="05">05</option>
                <option value="06">06</option>
                <option value="07">07</option>
                <option value="08">08</option>
                <option value="09">09</option>
                <option value="10">10</option>
              </select>
              <span>&nbsp; = &nbsp;$<span id="total"><%= number_with_precision(@campaign.fixed_payment_amount, precision: 2) %></span></span>

            </div>

            <input id="amount" type="hidden" name="amount" value="<%= number_with_precision(@campaign.fixed_payment_amount, precision: 2) %>" data-original="<%= number_with_precision(@campaign.fixed_payment_amount, precision: 2) %>"/>

          <% else %>

            <div class="amount_section">
            <h4 class="amount_header">Please enter an amount: </h4>
            <br/>
            <div class="amount_input" style="position:relative">
              <input id="amount" type="text" name="amount" value="<%= short_price(@reward.price) if @reward %>"/>&nbsp;&nbsp;
              <span style="position:absolute">$</span>
            </div>
            <span class="minimum">Minimum is $<%= number_with_precision(@campaign.min_payment_amount, precision: 2) %></span>
            <label class="error hide"></label>
            </div>
            <input id="quantity" type="hidden" name="quantity" value="1"/>

          <% end %>

          <% if @campaign.rewards? %>
            <div id="reward_select" data-reference="<%= @campaign.reward_reference %>">
            <h4>Select your <%= @campaign.reward_reference %>: </h4>
            <ul>
              <li class="reward_option active <%= raw('hide') if @reward %> clearfix" data-id="0" data-price="<%= short_price(@campaign.min_payment_amount) %>">
                  <input class="reward_input" type="radio" name="reward" value="0">
                  <label class="price"></label>
                  <div class="reward_description">
                    <p class="title">No <%= @campaign.reward_reference %></p>
                  </div>
                  <a class="reward_edit" href="#" style="display:none">edit</a>
              </li>
              <% @campaign.rewards.order("price ASC").each do |reward| %>
              <% if reward.visible? %>
                <li class="reward_option <%= raw('active') unless reward.sold_out? %> <%= ((@reward.id == reward.id) ? raw('selected') : raw('hide')) if @reward %> clearfix" data-id="<%= reward.id %>" data-price="<%= short_price(reward.price) %>">
                  <input class="reward_input" type="radio" name="reward" value="<%= reward.id %>" <%= raw('disabled') if reward.sold_out? %><%= raw('checked="checked"') if @reward && @reward.id == reward.id %>>
                  <label class="price">$<%= short_price(reward.price) %> +</label>
                  <div class="reward_description">
                    <p class="title"><%= reward.title %></p>
                    <p class="claimed">
                      <%= reward.payments.length %> <%= "of #{reward.number}" unless reward.unlimited? %> claimed
                      <% if reward.sold_out? %> (All gone!) <% end %>
                    </p>
                    <p class="description"><%= reward.description %></p>
                    <p class="delivery">Estimated Delivery: <%= reward.delivery_date %></p>
                  </div>
                  <a class="reward_edit" href="#" style="<%= 'display:none' unless @reward && @reward.id == reward.id %>">edit</a>
                </li>
              <% end %>
              <% end %>
            </ul>
            </div>
          <% end %>


          <button type="submit" class="btn btn-primary" id="continue_to_checkout">Continue to checkout</button>

        </form>
      </div>

    </div>

    <div class="sidebar">
      <div class="custom_content">
        <%= raw(@campaign.checkout_sidebar_content) %>
      </div>
    </div>

  </div>
</div>

app/views/campaigns/checkout_payment.html.erb
<div id="checkout">
  <div class="container content_box clearfix">
    <div class="main_content">
      <h3><a href="<%= campaign_home_path(@campaign) %>"><%= @campaign.name %></a></h3>

    <div class="well checkout_block" style="padding-bottom: 16px">

        <form accept-charset="UTF-8" action="<%= checkout_process_path(@campaign) %>" method="post" id="payment_form">

          <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
          <h4 class="contact">Contact Information</h4>

          <fieldset>
          <label for="fullname">Full Name</label>
          <input id="fullname" name="fullname" type="text">

          <label for="email">Email Address</label>
          <input id="email" name="email" type="text">

          <% if @campaign.collect_additional_info %>
          <h4>Additional Information</h4>

          <label for="additional_info"><%= @campaign.additional_info_label %></label>
          <textarea id="additional_info" name="additional_info"></textarea>
          <% end %>
          </fieldset>

          <% if @campaign.collect_shipping %>
          <h4>Shipping Address</h4>

          <fieldset>
            <div>
              <label for="address_one">Address1</label>
              <input id="address_one" name="address_one" type="text">

              <label for="address_two">Address2</label>
              <input id="address_two" name="address_two" type="text">
            </div>
          </fieldset>
          <fieldset>
            <div class="pull-left" style="margin-right: 14px">
              <label for="city">City</label>
              <input id="city" name="city" type="text" style="width:225px">
            </div>
            <div class="pull-right">
              <label for="state">State/Province/Region</label>
              <input id="state" name="state" type="text" style="width:225px">
            </div>
          </fieldset>
          <fieldset>
            <div class="pull-left" style="margin-right: 14px">
              <label for="postal_code">Postal Code</label>
              <input id="postal_code" name="postal_code" type="text" style="width:225px">
            </div>
            <div class="pull-right">
              <label for="country">Country</label>
              <select id="country" name="country" style="width:240px">
                 <option value="" selected>--</option>
                 <option value="USA" >United States</option>
                <% (IsoCountryCodes.all.map {|code| [code.name, code.alpha3]}).sort.each do |country| %>
                <option value="<%= country[1] %>"><%= country[0] %></option>
                <% end %>
              </select>
            </div>
          </fieldset>
          <% end %>

          <h4>Credit/Debit Card <i class="icon icon-lock show_tooltip" data-placement="top" data-title="Payments are encrypted"></i></h4>

          <fieldset>
            <div class="clearfix">
              <div class="card_number pull-left" style="margin-right:15px">
                <label for="card_number">Card Number</label>
                <input name="card_number" id="card_number" type="text" style="width:225px" autocomplete="off">
              </div>
              <div class="pull-left">
                <label>Expiration</label>
                <select id="expiration_month" style="width:118px">
                  <option value="01" selected>01</option>
                  <option value="02">02</option>
                  <option value="03">03</option>
                  <option value="04">04</option>
                  <option value="05">05</option>
                  <option value="06">06</option>
                  <option value="07">07</option>
                  <option value="08">08</option>
                  <option value="09">09</option>
                  <option value="10">10</option>
                  <option value="11">11</option>
                  <option value="12">12</option>
                </select>
                <select id="expiration_year" style="width:118px">
                  <option value="2013">2013</option>
                  <option value="2014" selected>2014</option>
                  <option value="2015">2015</option>
                  <option value="2016">2016</option>
                  <option value="2017">2017</option>
                  <option value="2018">2018</option>
                  <option value="2019">2019</option>
                  <option value="2020">2020</option>
                  <option value="2021">2021</option>
                  <option value="2022">2022</option>
                  <option value="2023">2023</option>
                </select>
              </div>
            </div>
            </fieldset>
            <fieldset>
              <div class="clearfix">
                <div class="pull-left" style="margin-right: 15px;">
                  <label for="security_code">Security Code <i class="icon icon-question-sign show_tooltip" data-placement="top" data-title="3 or 4 digit number"></i></label>
                  <input id="security_code" name="security_code" type="text"  style="width:225px" autocomplete="off">
                </div>
                <div class="billing_postal_code pull-left">
                  <label for="billing_postal_code">Billing Postal Code</label>
                  <input id="billing_postal_code" name="billing_postal_code" type="text"  style="width:225px">
                </div>
              </div>
            </fieldset>
          <label for="card_number" class="error" style="display: none"></label>
          <label for="security_code" class="error" style="display: none"></label>
          <label for="billing_postal_code" class="error" style="display: none"></label>

          <input id="ct_user_id" type="hidden" name="ct_user_id" value="<%= @campaign.production_flag ? @settings.ct_production_guest_id : @settings.ct_sandbox_guest_id %>" >

          <input id="quantity" type="hidden" name="quantity" value="<%= @quantity %>">
          <input id="amount" type="hidden" name="amount" value="<%= @amount %>">
          <input id="fee" type="hidden" name="fee" value="<%= @fee %>">
          <input id="reward" type="hidden" name="reward" value="<%= @reward ? @reward.id : '0' %>">
          <input id="client_timestamp" type="hidden" name="client_timestamp" value="">

          <% if !@campaign.production_flag %>
            <div style="color: red; margin-top: 10px;">This campaign is in sandbox mode, your card will not actually be charged.</div>
          <% end%>

          <div class="payment-submit">
            <button class="btn btn-primary show_loader" type="submit" data-total="<%= number_with_precision(@total, precision: 2) %>" data-loader="payment_form">Confirm payment of $<%= number_with_precision(@total, precision: 2) %></button>
            <span class="loader" data-loader="payment_form" style="display:none"></span>
            <div id="refresh-msg" style="display: none; color: red; margin-top: 10px">Your payment is being processed! Please do not refresh this page.</div>
          </div>

        </form>
        <div id="errors" style="display: none"></div>

        <div style="text-align: right; margin-right: -16px"><%= image_tag 'crowdtilt_badge_no_card_logos.png', width: "120px", height: "36px" %></div>
    </div>

  </div>

    <div class="sidebar">
      <div class="crowdtilt-powered clearfix">
        <%= image_tag 'crowdtilt_badge.png', width: "317px", height: "36px" %>
      </div>
      <div class="well">
        <div class="clearfix">
          <h4 class="pull-left">Payment Summary</h4>
          <p class="pull-right"><%= link_to "edit", checkout_amount_path(@campaign) %></p>
        </div>

        <table style="width: 100%">

          <tr>
          <td width="225">
          <% if @campaign.payment_type == "fixed" %>
            <p>Subtotal (<%= "#{@quantity} x $#{number_with_precision(@campaign.fixed_payment_amount, precision: 2)}" %>)</p>
          <% else %>
            <p>Subtotal</p>
          <% end %>
          </td>
          <td style="text-align: right"><p>$<%= number_with_precision(@amount, precision: 2) %> </p></td>
          </tr>

          <% if @fee > 0 %>
          <tr>
          <td width="225"><p>Processing Fee</p></td>
          <td style="text-align: right"><p>$<%= number_with_precision(@fee, precision: 2) %></p></td>
          </tr>
          <% end %>

          <tr>
          <td width="225"><p><strong>Total</strong></p></td>
          <td style="text-align: right"><p><strong>$<%= number_with_precision(@total, precision: 2) %></strong></p></td>
          </tr>

          <% if !@campaign.production_flag %>
          <tr>
          <td colspan='2' ><p>*This campaign is in sandbox mode, your card will not actually be charged.</p></td>
          </tr>
          <% end %>

        </table>

      </div>

      <% if @campaign.rewards? %>
      <div class="well rewards">
        <h4><%= @campaign.reward_reference.titleize %> Selected</h4>
        <% if @reward %>
          <p><strong><%= "#{@reward.title} ($#{short_price(@reward.price)})" %></strong></p>
          <p><%= @reward.description %></p>
          <p>Estimated Delivery: <%= @reward.delivery_date %></p>
        <% else %>
          <p>None</p>
        <% end %>
      </div>
      <% end %>

      <div class="custom_content">
        <%= raw(@campaign.checkout_sidebar_content) %>
      </div>
    </div>

  </div>
</div>

<%= javascript_include_tag "https://api.crowdtilt.com/v1/js/crowdtilt.js" %>
<%= javascript_tag do %>
  crowdtilt.init('<%= @campaign.production_flag ? 'production' : 'sandbox' %>')
<% end %>