config/routes.rb
Crowdhoster::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  # PAGES
  root                                         to: 'pages#index'

  # USERS
  devise_for :users, { path: 'account', controllers: { registrations: :registrations } }  do
    match '/user/settings',                    to: 'devise/registrations#edit',             as: :user_settings
  end

  # ADMIN
  match '/admin',                      to: 'admin#admin_website',                   as: :admin_website
  namespace :admin do
    resources :campaigns
    post '/payments/:id/refund',                to: 'payments#refund_payment',               as: :admin_payment_refund
  end

  match '/admin/campaigns/:id/copy',           to: 'admin/campaigns#copy',                  as: :admin_campaigns_copy
  match '/admin/campaigns/:id/payments',       to: 'admin/campaigns#payments',              as: :admin_campaigns_payments
  match '/admin/processor-setup',              to: 'admin#admin_processor_setup',           as: :admin_processor_setup
  post '/admin/bank-setup',                    to: 'admin#create_admin_bank_account',       as: :create_admin_bank_account
  get '/admin/bank-setup',                     to: 'admin#admin_bank_account',              as: :admin_bank_account
  delete '/admin/bank-setup',                  to: 'admin#delete_admin_bank_account',       as: :delete_admin_bank_account
  match '/admin/notification-setup',           to: 'admin#admin_notification_setup',        as: :admin_notification_setup
  match '/ajax/verify',                        to: 'admin#ajax_verify',                     as: :ajax_verify

  # CAMPAIGNS
  match '/:id/checkout/amount',                to: 'campaigns#checkout_amount',             as: :checkout_amount
  match '/:id/checkout/payment',               to: 'campaigns#checkout_payment',            as: :checkout_payment
  match '/:id/checkout/process',               to: 'campaigns#checkout_process',            as: :checkout_process
  match '/:id/checkout/confirmation',          to: 'campaigns#checkout_confirmation',       as: :checkout_confirmation
  match '/:id',                                to: 'campaigns#home',                        as: :campaign_home


  namespace :api, defaults: {format: 'json'} do
    scope module: :v0  do
      resources :campaigns, only: :show do
        resources :payments, only: :index
      end
    end
  end
end

app/views/layouts/_facebook_metas.html.erb
<meta property='og:type' content="website" />
<meta property='og:site_name' content="<%= @settings.facebook_title.blank? ? @settings.site_name : @settings.facebook_title %>" />
<meta property='fb:app_id' content="<%= @settings.facebook_app_id.present? ? @settings.facebook_app_id : 331145500360318 %>" />

<% params[:controller] == 'campaigns' ? c = @campaign : c = false %>

<% if c %>
  <meta property='og:title' content="<%= c.facebook_title.blank? ? c.name : c.facebook_title %>" />
  <meta property='og:url' content="<%= url_for campaign_home_url(c) %>" />
  <% if !c.facebook_description.blank? %>
    <meta property='og:description' content="<%= c.facebook_description %>" />
  <% elsif !@settings.facebook_description.blank? %>
    <meta property='og:description' content="<%= @settings.facebook_description %>" />
  <% end %>
  <% if c.facebook_image.file? %>
    <meta property='og:image' content='<%= c.facebook_image.url %>' />
  <% elsif @settings.facebook_image.file? %>
    <meta property='og:image' content='<%= @settings.facebook_image.url %>' />
  <% end %>
<% else %>
  <meta property='og:title' content="<%= @settings.facebook_title.blank? ? @settings.site_name : @settings.facebook_title %>" />
  <meta property='og:url' content="<%= root_url %>" />
  <% if !@settings.facebook_description.blank? %>
    <meta property='og:description' content="<%= @settings.facebook_description %>" />
  <% end %>
  <% if @settings.facebook_image.file? %>
    <meta property='og:image' content='<%= @settings.facebook_image.url %>' />
  <% end %>
<% end %>

app/views/layouts/_google_analytics.html.erb
<script type="text/javascript">
  <% if Rails.env.development? %>
  window['ga-disable-UA-38090057-1'] = true;
  <% if !@settings.google_id.blank? %>
  window['ga-disable-<%= @settings.google_id %>'] = true;
  <% end %>
  <% end %>

  var _gaq = _gaq || [];
  _gaq.push(
    ['_setAccount', 'UA-38090057-1'],
    ['_setDomainName', 'crowdhoster.com'],
    ['_trackPageview']<% if !@settings.google_id.blank? %>,
    ['b._setAccount', '<%= @settings.google_id %>'],
    ['b._trackPageview']<% end %>
  );

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    <% if Rails.env.development? %>
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/u/ga_debug.js';
    <% else %>
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    <% end %>
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

app/views/layouts/_mobile_bookmark_metas.html.erb
<!-- iOS and Android Bookmarks -->
<meta name="apple-mobile-web-app-title" content="<%= @settings.site_name %>">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="<%= asset_path 'app_icon_114px.png' %>" />
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="<%= asset_path 'app_icon_144px.png' %>" />
<link rel="apple-touch-icon-precomposed" href="<%= asset_path 'app_icon_172px.png' %>" />

app/views/layouts/_navbar.html.erb
<% if user_signed_in? && current_user.admin? %>
<div id="navbar">
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container clearfix">
      <ul class="nav pull-left">

         <% if current_page?(root_path) %>
           <li>
             <a href="<%= url_for admin_website_path %>"><i class="icon-edit icon-white"></i> Edit homepage</a>
           </li>
           <li>
              <a href="<%= url_for new_admin_campaign_path %>"><i class="icon-plus icon-white"></i> New Campaign</a>
           </li>
         <% end %>

         <% if request.fullpath.include? 'admin' %>
           <li>
             <a href="<%= url_for root_path %>"><i class="icon-chevron-left icon-white"></i> Back to website</a>
           </li>
           <li>
              <a href="<%= url_for new_admin_campaign_path %>"><i class="icon-plus icon-white"></i> New Campaign</a>
           </li>
         <% end %>

         <% if params[:controller] == 'campaigns' %>
           <li>
             <a href="<%= edit_admin_campaign_path(@campaign) %>"><i class="icon-edit icon-white"></i> Edit campaign</a>
           </li>

           <% if !@campaign.published_flag %>
             <li class="status red show_tooltip" data-placement="bottom" data-title="Visible to ADMINS ONLY">
               Not published
             </li>
           <% else %>
             <li class="status green show_tooltip" data-placement="bottom" data-title="Visible to ALL">
               Published
             </li>
           <% end %>

           <% if !@campaign.production_flag %>
             <li class="status red show_tooltip" data-placement="bottom" data-title="Transactions WILL NOT be processed">
               Sandbox payments
             </li>
           <% else %>
             <li class="status green show_tooltip" data-placement="bottom" data-title="Transactions WILL be processed">
               Payments activated
             </li>
           <% end %>

         <% end %>

       </ul>

        <ul class="nav pull-right">
            <li class="dropdown">
              <%= image_tag 'user_icon.png' %>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.fullname %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu pull-right" role="menu">
                <li><%= link_to "Account", user_settings_path %></li>
                <li><%= link_to "Admin", admin_website_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: "delete" %></li>
              </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="spacer" style="height:30px; width: 100%"></div>
</div>
<% end %>

app/views/layouts/_social_js.html.erb
<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '<%= @settings.facebook_app_id.present? ? @settings.facebook_app_id : 331145500360318 %>',
      status     : true,
      xfbml      : true
    });
  };

  // Load the SDK asynchronously
  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/all.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

<script>
!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
</script>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
    <title><%= @settings.site_name %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= render 'layouts/google_analytics' %>
  </head>
  <!--[if lt IE 9 ]><body class="lt-ie9"><![endif]-->
  <!--[if (gt IE 9)|!(IE)]><!--> <body><!--<![endif]-->
    <%= render 'layouts/navbar' %>
    <% flash.each do |key, value| %>
      <div class="admin-alert alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <div id="main">
      <%= yield %>
    </div>
    <%= render 'admin/footer' %>

    <div id="powered">
      <a href="http://www.latcoin.com">&nbsp;&nbsp;A Startup Chile site</a>
    </div>

    <!--<% if Rails.env.development? %>
      <div id="debug" style="background: white; padding:50px"><%= debug(params) %></div>
    <% end %>-->

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
    <title><%= @settings.site_name %></title>
    <% if @settings.indexable == false %>
      <meta name="robots" content="noindex, nofollow">
    <% end %>
    <%= render 'layouts/facebook_metas' %>
    <%= render 'layouts/mobile_bookmark_metas' %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    "application" %>
    <style type="text/css"><%= raw(@settings.custom_css) %></style>

    <%= javascript_include_tag "application" %>
    <%= render 'layouts/google_analytics' %>
  </head>
  <!--[if lt IE 9 ]><body class="lt-ie9"><![endif]-->
  <!--[if (gt IE 9)|!(IE)]><!--> <body><!--<![endif]-->
    <%= render 'layouts/social_js' %>
    <%= render 'layouts/navbar' %>
    <%= render 'theme/views/header' %>
    <% flash.to_hash().slice(:success, :info, :notice, :error).each do |key, value| %>
      <% if !value.blank? %><div class="alert alert-<%= key %>"><%= value %></div><% end %>
    <% end %>
    <div id="main">
      <%= yield %>
    </div>
    <%= render 'theme/views/footer' %>

    <div id="powered">
      <a href="http://www.latcoin.com">&nbsp;&nbsp;A Startup Chile site</a>
    </div>

    <% if Rails.env.development? %>
      <div id="debug" style="background: white; padding:50px"><%= debug(params) %></div>
    <% end %>

    <%= raw(@settings.custom_js) %>
    <script type="text/javascript" src="//assets.pinterest.com/js/pinit.js"></script>
  </body>
</html>

app/views/layouts/default_mailer.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
  </head>
  <body>
    <p style="font-size: 16px; color: black"><%= @settings.site_name %></p>
    <hr>
    <br/>
    <%= yield %>
    <br/>
    <hr>
    <p style="text-align: center;">
    <a style="text-decoration: none; color: black" href="http://www.crowdhoster.com" target="_blank">&nbsp;&nbsp;A Crowdhoster Site</a>
    <a style="text-decoration: none; color: black" href="http://www.crowdhoster.com" target="_blank">
      &nbsp;<img height="15px;" style="margin-bottom: -2px;" src="https://crowdhoster-emails.s3.amazonaws.com/crowdtiltcircle.png">&nbsp;
    </a>
    <a style="text-decoration: none; color: black" href="http://www.crowdtilt.com" target="_blank">Powered by Crowdtilt</a>
    </p>
    <p style="text-align: center;"><a style="text-decoration:none;" href="http://www.crowdhoster.com">[Start your own campaign]</a></p>
  </body>
</html>